#!/bin/bash

# Get the number of resource events generated by a manifest that is not a managed resource. Typically recursive file or tidy files. Useful for looking for a large resource_events table. 

puppet query 'events[file, count()] { (!resource_title in resources[title]{}) group by file}'
